/**
 * Сегменты путей под `api/v1` (как в smartlib_backend).
 * Используются в ApiResource: `new ApiResource(client, ApiPaths.works)`.
 */
export const ApiPaths = {
  users: 'users',
  usersAuth: 'users/auth',
  usersAuthToken: 'users/auth/token',
  usersAuthTokenRefresh: 'users/auth/token/refresh',
  usersAuthLogin: 'users/auth/login',
  usersAuthRegister: 'users/auth/register',
  usersAuthLogout: 'users/auth/logout',
  usersAuthResetPassword: 'users/auth/reset-password',
  usersProfile: 'users/profile/get-profile',
  usersStaff: 'users/staff',
  authors: 'authors',
  works: 'works',
  worksSimilar: 'works/similar',
  genre: 'works/genre',
  workItems: 'works/work-items',
  workItemsByLibrary: 'works/work-items/by-library',
  workItemsByWork: 'works/work-items/by-work',
  workItemsAvailabilityByWork: 'works/work-items/availability-by-work',
  libs: 'libs',
  libBranch: 'libs/branch',
  workLoans: 'work-loans',
  positions: 'positions',
  inventory: 'inventory',
  inventoryMovements: 'inventory/movements',
  suppliers: 'suppliers',
  amenities: 'amenities',
  amenityVendors: 'amenities/vendors',
  feedbackWorks: 'feedback/works',
  feedbackLibs: 'feedback/libs',
} as const;
